name: canvasdrawing
description: "A Flutter drawing app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  speech_to_text:
    path: packages/speech_to_text/speech_to_text
  cupertino_icons: ^1.0.6
  http: 1.2.2
  flutter_dotenv: ^5.2.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/login.png
    - assets/End.png
    - assets/Privacy.png
    - assets/Question_bg.png
    - assets/house_intro_background.png
    - assets/tree_intro_background.png
    - assets/person_intro_background.png
    - assets/Men_Intro_bg.png
    - assets/Women_Intro_bg.png
    - assets/pencil.png
    - assets/eraser.png
    - assets/Cloud.png
    - assets/mic_bg.png
    - assets/mic.png
    - assets/Rectangle.png
    - assets/reset_icon.png
    - assets/exercise.png
    - assets/house_tree.png
    - assets/photo.png
    - assets/집을.png
    - assets/나무를.png
    - assets/남자를.png
    - assets/여자를.png
    - assets/그려봐!.png

  fonts:
    - family: TJJoyofsingingEB_TTF
      fonts:
        - asset: assets/fonts/TJJoyofsingingEB_TTF.ttf
